Proyecto/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FantasyController@index')->name('index');
Route::get('/search', 'FantasyController@search');

//Route::resource('','GeneralController');
//Route::get('/display', 'GameController@display')->name('display');

Route::resource('fantasy', 'FantasyController')->except([
    'index'
]);
Route::resource('display', 'GameController');

Route::resource('mock', 'QuizController');

Route::resource('login', 'LoginController');

Route::post('fantasy/create', 'FantasyController@storeAjax');

Route::post('fantasy/modalFields', 'FantasyController@modalAjax');


Route::post('activepoint/create', 'ActivePointController@storeAjax');

Route::post('activepoint/modalFields','ActivePointController@modalAjax');

Route::post('activepoint/delete/', 'ActivePointController@deleteAjax');



Route::post('quiz/fantasy','QuizController@storeAjaxFantasy');

Route::post('quiz/activePoint','QuizController@storeAjaxAP');

Route::post('quiz/APModalFields','QuizController@modalAPAjax');

Route::post('quiz/FantasyModalFields', 'QuizController@modalFantasyAjax');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Proyecto/resources/views/create-fantasy.blade.php
@include('doc_header')
@include('site_header')
<div class="container fantasy-style">
   <h1 class="mt-4 mb-3 gradiant-tittle">CREATE YOUR OWN FANTASY</h1>
   <div class="pt-25"></div>
   <div class="mlr">
   <div class="row">
     <div class="col-2 menu-pactivo">
           <ul class="ls-none">

         <li><a tittle="Click to open a background selector" id="addBack" ><img class="img-fluid icon-pa" src="assets/stimey/graphics/icons/ICON-Post-File.png"></a></li>
         <li><a title="Click to create active point" id="create"><img class="img-fluid icon-pa" src="assets/stimey/graphics/icons/ICON-Review-Star-Technology.png"></a></li>
       </ul>

   </div>

   <div id="workspace" class="col-9 offset-1 ui-widget-content ">
       <div id="area" class="row">

       </div>
     </div>
 </div>

 </div>

 </div>

 </div>


<div id="modalBack" class="modalWindow">
         <div class="modal-content">
           <div class="modal-header">
             <span class="close">&times;</span>
           </div>
           <div class="modal-body">
              <div class="row">
               <div class="col-4 offset-1">
                 <input class="jscolor {styleElement:'workspace'}" id="colorpicker" name="color" pattern="^#+([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$" value="#ffffff">
                 <input type="hidden" pattern="^#+([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$" value="#ffffff" id="hexcolor"></input>
             </div>
               <div class="col-2"> OR </div>
               <div class="col-4">
                 <input type="file" id="uploadBack">
               </div>
             </div>
           </div> <!-- /.modal-body -->

           <div class="modal-footer">
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
               <a  class="btn btn-primary" id="save">Save changes</a>
           </div> <!-- /.modal-footer -->


           </div> <!-- /.modal-content -->

</div> <!-- /.modal -->


<div id="modalPA" class="modalWindow"> <!-- modal punto activo -->
   <div class="modal-content">
       <span class="close" id="exit">&times;</span>
       <h3 class="mt-4 mb-3 gradiant-tittle">Configure the active point</h3>
   <form action="" enctype="multipart/form-data">
   <div class="row">
     <div class="col-12 col-sm-6">
       <label class="form-label"><strong>Image</strong><input type="file" name="img"></label>

     </div>
     <div class="col-12 col-sm-6">
       <label class="form-label"><strong>Description(Image)</strong><input type="text" name="imgDescription"></label>

     </div>
     <div class="col-12 col-sm-6">
       <label class="form-label"><strong>Video url</strong><input type="text" name="videoUrl"></label>

     </div>
     <div class="col-12 col-sm-6">
       <label class="form-label"><strong>Order</strong>
       <select name="order">
           <option>1</option>
           <option>2</option>
           <option>3</option>
       </select>
       </label>

     </div>

     <div class="col-12">
       <label class="form-label"><strong>Complementary text</strong>
       <textarea rows="4" name="complementaryText">
       </textarea>
       </label>
     </div>



   </div>
   </form>
   </div>
</div>
<div class="box invisible">
   <a id="alerta1" class="button" href="#popup1">Let me Pop up</a>
</div>

<div id="popup1" class="overlay">
   <div class="popup">
       <h2>Sorry!</h2>
       <a class="close" href="#">&times;</a>
       <div class="content">
           You can't add more active points!
       </div>
   </div>
</div>

<style>
.box {
 width: 40%;
 margin: 0 auto;
 background: rgba(255,255,255,0.2);
 padding: 35px;
 border: 2px solid #fff;
 border-radius: 20px/50px;
 background-clip: padding-box;
 text-align: center;
}

.overlay {
 position: fixed;
 top: 0;
 bottom: 0;
 left: 0;
 right: 0;
 background: rgba(0, 0, 0, 0.7);
 transition: opacity 500ms;
 visibility: hidden;
 opacity: 0;
}
.overlay:target {
 visibility: visible;
 opacity: 1;
}

.popup {
 margin: 70px auto;
 padding: 20px;
 background: #fff;
 border-radius: 5px;
 width: 30%;
 position: relative;
 transition: all 5s ease-in-out;
}

.popup h2 {
 margin-top: 0;
 color: #F4B12A;
 font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
 position: absolute;
 top: 20px;
 right: 30px;
 transition: all 200ms;
 font-size: 30px;
 font-weight: bold;
 text-decoration: none;
 color: #F4B12A ;
}
.popup .close:hover {
 color: #06D85F;
}
.popup .content {
 max-height: 30%;
 overflow: auto;
 color: #90D400 ;
}

@media screen and (max-width: 700px){
 .box{
   width: 70%;
 }
 .popup{
   width: 70%;
 }
}
</style>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script type="text/javascript">


   var PA = "<div class='punto-Activo ui-widget-content'; ondblclick='openmodal(this);'></div>" ;
   var i = 0;
   $( "#create" ).click(function( ) {
     if(i != 10){
         $(PA).attr('id','PA'+i).appendTo( "#area" ).draggable({containment: "parent"}).resizable({ghost: true, autoHide: true}).css({"background-color": "#C5D8FF","height":"50px", "width":"50px", "max-height": "400px",  "max-height": "400px", "border": "1px solid black"});
         i++;
       } else{
     x = window.location.href;
         window.location.href = "#popup1";
     window.location.replace = x;
       }
     });

   //modal background script

   var modal = document.getElementById('modalBack');

 var btn = document.getElementById("addBack");

 var span = document.getElementsByClassName("close")[0];

 btn.onclick = function() {
   modal.style.display = "block";
 }

 span.onclick = function() {
   modal.style.display = "none";
 }

 window.onclick = function(event) {
   if (event.target == modal) {
     modal.style.display = "none";
   }
 }

 function openmodal(elemento){
   var mod = document.getElementById('modalPA');

   var bt = document.getElementById(elemento.id);

   var sp = document.getElementById("exit");

   bt.ondblclick = function() {
     mod.style.display = "block";
   }

   sp.onclick = function() {
     mod.style.display = "none";
   }

   window.onlclick = function(event) {
     if (event.target == modal) {
       mod.style.display = "none";
    }
   }
 }


 function posicion(div) {
   var elemento = $(".midiv");
   var posicion = elemento.position();
   alert( "left: " + posicion.left + ", top: " + posicion.top );
 }

</script>

 @include('site_footer')

Proyecto/resources/views/doc_header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>STIMEY - Fantasy Project</title>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
  <script src="{{ asset ('jquery/jquery.min.js') }}"></script>
  <script src="{{ asset ('bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ asset ('jquery/jquery-ui.min.js') }}"></script>
  <script src="{{ asset ('jquery/jquery.ui.touch-punch.min.js') }}"></script>
  <script src="{{ asset ('/jquery/jscolor.js') }}"></script>

  <link href="{{ asset ('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset ('jquery/jquery-ui css/jquery-ui.min.css') }}" rel="stylesheet">
  <link href="{{ asset ('jquery/jquery-ui css/jquery-ui.structure.min.css') }}" rel="stylesheet">
  <link href="{{ asset ('jquery/jquery-ui css/jquery-ui.theme.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <meta name="csrf-token" content="{{ csrf_token() }}">



  <!-- Bootstrap core CSS -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- NUESTROS CSS -->
  <link href="{{ asset ('css/modern-business.css') }}" rel="stylesheet">
  <link href="{{ asset ('css/stimey.css') }}" rel="stylesheet">

  <link href="{{ asset ('css/modal.css') }}" rel="stylesheet">

  <link href="{{ asset ('css/modales.css') }}" rel="stylesheet">



  <!-- Quill -->
  <script src="{{asset ('quill/quill.js')}}"></script>
  <script src="{{asset ('quill/quill.min.js')}}"></script>
  <link rel="stylesheet" href="{{asset ('quill/quill.snow.css')}}">

  <!-- Katex -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" integrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij" crossorigin="anonymous"></script>

  <!-- HightLight -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Resizeable and draggable  -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  

</head>

Proyecto/resources/views/fantasy.blade.php
@include('doc_header')
@include('site_header')

  <!-- Page Content -->
  <div class="container fantasy-style">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3 gradiant-tittle">*TITULO FANTASIA*
      <small>*SUBITUTLO*</small>
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/profile">*MIS FANTASIAS*</a>
      </li>
      <li class="breadcrumb-item active">*TITULO FANTASIA ACTUAL*</li>
    </ol>

    <!-- Portfolio Item Row -->
    <div class="row">

      <div class="col-md-8">
        <img class="img-fluid" src="http://placehold.it/750x500" alt="">
      </div>

      <div class="col-md-4">
        <h3 class="my-3">Project Description</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
        <h3 class="my-3">Project Details</h3>
        <ul>
          <li>Lorem Ipsum</li>
          <li>Dolor Sit Amet</li>
          <li>Consectetur</li>
          <li>Adipiscing Elit</li>
        </ul>
      </div>

      <div class="col-12 pt-25">
          <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-12 col-sm-4">
            <a class="btn btn-lg btn-secondary btn-block" href="#">Edit it</a>
        </div>
        <div class="col-sm-4"></div>
        </div>
      </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <!-- EN PRINCIPIO ESTO PODRIA SER UTIL PARA MAS INFO
	<h3 class="my-4">Related Projects</h3>

    <div class="row">

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

    </div>
	-->


    <!-- /.row -->

  </div>
  <!-- /.container -->

@include('site_footer')

Proyecto/resources/views/home.blade.php
@extends('layout.general')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Proyecto/resources/views/index.blade.php
@extends('layout.general')
@section('content')
<!-- Page Content -->
<section>
	<div class="container">
		<div class="row">
			@include('site_menu')
			<div class="col-md-8 col-lg-9 mb-4 text-center">
				<div class="card-header">
					<div class="col-12">
						<ul class="ls-none location">
							<li class="active-text">
								<h5 class="text-custom">My fantasies</h5>
							</li>
							<li class="text-custom">
								<a href="/search">
									<h5 class="text-custom">Discover</h5>
								</a>
							</li>
						</ul>
					</div>
				</div>

				<div class="card-container">
					<div class="col-12 card-header-with-border">
						<h5><img src="{{asset('assets/stimey/graphics/icons/ICON-PROFILE_circle.png')}}" class="img-fluid icon-pa"> My Fantasies</h5>
					</div>
					<hr class="barra">
					<div class="row">
						@if($fantasies->count())
						@foreach ($fantasies as $fantasy)
						<!--Pongo un ejemplo para copiar estilos al dinamizarlo-->
						<div class="col-lg-4 col-sm-6 portfolio-item">
							<div class="card h-100">
								@if(!$fantasy->image)
								<a href="#"><img class="card-img-top" src="{{ asset ('assets/stimey/stimyverse/CRASH PLANET_Landscape_02.png') }}" alt=""></a>
								@else
								<a href="#"><img class="card-img-top" src="{{$fantasy->image}}" alt=""></a>
								@endif

								<div class="card-body">
									<h4 class="card-title">
										<h5>{{$fantasy->name}}</h5>
									</h4>
									@if($fantasy->description)
									<div id="fant-desc" class="card-text">
										{!! $fantasy->description !!}
									</div>

									@else
									<p class="card-text">This fantasy does not have a description</p>
									@endif
									<hr class="barra">
									<!--<a class="btn-fantasy nav-link" href="#">Try</a>-->
									<div class="mt-3">
										<div class="clearfix custom-display">
											<a class="btn btn-primary btn-xs btn-edit" href="{{action('FantasyController@edit', $fantasy->id)}}" ><span></span><img src="{{asset('assets/stimey/graphics/icons/BTN-Edit-circle.png')}}" class="icon-header"></a>
											<form action="{{action('FantasyController@destroy', $fantasy->id)}}" method="post">
												{{csrf_field()}}
												<input name="_method" type="hidden" value="DELETE">
												<button class="btn btn-danger btn-xs btn-delete" type="submit"><span><img src="{{asset('assets/stimey/graphics/icons/ICON_Delete-Post.png')}}" class="icon-header"></span></button>
											</form>
										</div>
										<div class="mt-3">
											<a tittle="Play this fantasy" class="btn-fantasy nav-link" href="{{action('GameController@show', $fantasy->id)}}"><span><img src="{{asset('assets/stimey/graphics/icons/ICON_SERIOUS-GAMES_square.png')}}" class="icon-header"></span></a>
										</div>

									</div>
								</div>
							</div>
						</div>
						@endforeach
						@else
						<h4></h4>
						<div class="container">
							<hr></hr>
							<h5> You haven't create any fantasy yet !</h5>
							<hr></hr>
						</div>
						@endif
					</div>

					<div class="col-12 card-header-with-border">
						<h5><img src="{{asset('assets/stimey/graphics/icons/ICON-Progress_Thumb-up-badge.png')}}" class="img-fluid icon-pa"> Active Fantasies</h5>
					</div>
					<hr class="barra">
					<div class="col-lg-4 col-sm-6 portfolio-item">
						<div class="card h-100">
							<a href="#"><img class="card-img-top" src="assets/imgs/myfantasies/cicloagua.jpg" alt=""></a>
							<div class="card-body">
								<h4 class="card-title">
									<h5>Fantasía Ciclo del agua</h5>
								</h4>
								<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
								<hr class="barra">
								<a class="btn-fantasy nav-link" href="{{action('GameController@show', '666')}}">Try</a>
							</div>
						</div>
					</div>


				</div>
			</div>
		</div>

	</div>
</section>
@endsection

Proyecto/resources/views/main.blade.php
@include('doc_header')
@include('site_header')
  <!-- Page Content -->
<div class="container">
	<div class="row">
		@include('site_menu')
		<div class="col-md-8 col-lg-9 mb-4 text-center">
			<div class="card-header">
				<div class="col-12">
					<ul class="ls-none location">
						<li class="active-text">
							<h5 class="text-custom">My fantasies</h5>
						</li>
						<li class="text-custom">
							<a href="/search">
								<h5 class="text-custom">Discover</h5>
							</a>
						</li>
					</ul>
				</div>
			</div>

			<div class="card-container">
				<div class="col-12 card-header-with-border">
					<h5>My fantasies</h5>
				</div>
				<hr class="barra">
				<!--Pongo un ejemplo para copiar estilos al dinamizarlo-->
				<div class="col-lg-4 col-sm-6 portfolio-item">
        				<div class="card h-100">
          					<a href="#"><img class="card-img-top" src="assets/imgs/myfantasies/cicloagua.jpg" alt=""></a>
          				<div class="card-body">
            					<h4 class="card-title">
              						<h5>Fantasía Ciclo del agua</h5>
            					</h4>
            					<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
					<hr class="barra">
					<a class="btn-fantasy nav-link" href="#">Try</a>
          				</div>
        				</div>
      				</div>

			</div>
		</div>
	</div>

</div>

@include('site_footer')

Proyecto/resources/views/site_header.blade.php
<body>
  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top nav-fixed-top" id="dark-head">
    <div class="container">
      <a class="navbar-brand" href="/"><img src="http://promostimey.uca.es/wp-content/uploads/cropped-LogoStimeyWeb-2-e1482174847582.png" alt="Stimey"></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <!--
	  <li class="nav-item">
            <a class="nav-link" href="/myfantasy">My fantasy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/search">Search fantasy</a>
          </li>
	-->
          <li class="nav-item">
            <a title="Create fantasy" class="icon-header" href="{{ route('fantasy.create') }}"><img class="icon-header" src="{{ asset ('assets/stimey/graphics/icons/BTN-Add-circle.png') }}"></a>
          </li>

          @guest
              @if (Route::has('register'))
                  <li class="nav-item ml-4">
                      <a class="nav-link btn-primary-custom" href="{{ route('register') }}">{{ __('Register') }}</a>
                  </li>
              @endif
          @else
              <li class="nav-item dropdown df">
                  <a id="navbarDropdown" class="nav-link ml-3" href="#" role="button" >
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>
                  <a onclick="logout()" class="btn btn-danger ml-3" role="button" style="color: white;">
                      {{ __('Logout') }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <a id="logout" class="dropdown-item" href="{{ route('logout') }}"
                         onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
          @endguest
          <!--  MENU SUBYACENTE
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Portfolio
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Blog
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
              <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
              <a class="dropdown-item" href="blog-post.html">Blog Post</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Other Pages
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="full-width.html">Full Width Page</a>
              <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
              <a class="dropdown-item" href="faq.html">FAQ</a>
              <a class="dropdown-item" href="404.html">404</a>
              <a class="dropdown-item" href="pricing.html">Pricing Table</a>
            </div>
          </li>
          FIN MENU SUBYACENTE -->
        </ul>
      </div>
    </div>
  </nav>

  <script type="text/javascript">
    
    function logout(){
      $('#logout').click();
    }
  </script>

Proyecto/resources/views/site_menu.blade.php
<div class="col-md-4 col-lg-3 mb-4">
	<ul class="nav nav-pills nav-stacked d-inline-block text-left">
		
		<hr class="barra">
		
		<li class="element-menu">
			<a class="no-underline" href="/">
				<span> <img class="icon-menu" src="{{ asset('assets/stimey/graphics/icons/ICON-DASHBOARD_circle.png')}}">
				</span>
				<span class="text-menu"> Home
				</span>
			</a>
		</li>

		<hr class="barra">

		<li class="element-menu">
			<a class="no-underline" href="/search">
				<span> <img class="icon-menu" src="{{ asset('assets/stimey/graphics/icons/ICON_Add-Topic.png')}}">
				</span>
				<span class="text-menu"> Discover
				</span>
			</a>
		</li>

		<hr class="barra">		

		<li class="element-menu">
			<a class="no-underline" href="{{ route('fantasy.create') }}">
				<span> <img class="icon-menu" src="{{ asset('assets/stimey/graphics/icons/BTN-Add-circle.png')}}">
				</span>
				<span class="text-menu"> Create
				</span>
			</a>
		</li>
		
		<hr class="barra">

	</ul>
</div>